apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260620-234614-0uutf3rcwygx-service
spec:
  selector:
    app: enterprise-system-20260620-234614-0uutf3rcwygx
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
